/**
 * BMad Studio shared types
 * ========================
 *
 * Types and Zod schemas used across main / preload / renderer for the BMad
 * Studio engine-swap subsystem. Every CSV/YAML/TOML parse, every IPC payload,
 * and every external CLI output that touches the renderer goes through one of
 * the schemas in this file.
 *
 * Keep this file 100% framework-free: no Electron imports, no Node-only APIs.
 * The schemas need to be importable from the renderer for client-side
 * validation of cached IPC payloads.
 *
 * Doc citations live next to the type they ground:
 *   per BMAD docs § "What got installed" — manifest.yaml shape
 *   per BMAD docs § "Three-Layer Override Model" — customization layers
 *   per BMAD docs § "Merge Rules (by shape, not by field name)" — resolver semantics
 *   per `bmad-help/SKILL.md` § "CSV Interpretation" — bmad-help.csv schema
 *
 * See: apps/desktop/docs/bmad-migration/INVENTORY.md (§3 phase graph) +
 *      apps/desktop/docs/bmad-migration/DECISIONS.md (KAD-1..10 + D-NN)
 */

import { z } from 'zod';

// =============================================================================
// Phase + track + persona enumerations
// =============================================================================

/**
 * BMAD's four lifecycle phases plus the cross-cutting "anytime" bucket.
 * Per BMAD docs § "Understanding BMad" — Analysis / Planning / Solutioning /
 * Implementation. The "anytime" phase covers `bmad-help`, `bmad-document-project`,
 * `bmad-quick-dev`, `bmad-correct-course`, etc.
 */
export const BMAD_PHASES = [
  '1-analysis',
  '2-planning',
  '3-solutioning',
  '4-implementation',
  'anytime',
] as const;

export type BmadPhase = (typeof BMAD_PHASES)[number];

export const BmadPhaseSchema = z.enum(BMAD_PHASES);

/**
 * The three planning tracks per BMAD docs § "Three Planning Tracks".
 * Quick Flow ships in Phase 6 per D-005; Phases 1–5 only wire `method` and
 * `enterprise` into the orchestrator.
 */
export const BMAD_TRACKS = ['quick', 'method', 'enterprise'] as const;
export type BmadTrack = (typeof BMAD_TRACKS)[number];
export const BmadTrackSchema = z.enum(BMAD_TRACKS);

/**
 * Six hardcoded BMM personas. Slugs are stable identity per BMAD docs
 * § "What Named Agents Buy You" — the resolver cannot rename them via TOML
 * overrides ("agent.name" and "agent.title" are read-only).
 */
export const BMAD_PERSONA_SLUGS = [
  'mary',
  'paige',
  'john',
  'sally',
  'winston',
  'amelia',
] as const;

export type BmadPersonaSlug = (typeof BMAD_PERSONA_SLUGS)[number];
export const BmadPersonaSlugSchema = z.enum(BMAD_PERSONA_SLUGS);

/**
 * Persona identity sourced from `_bmad/config.toml` `[agents.bmad-agent-*]`
 * blocks (regenerated by the installer). The `customize.toml` per skill can
 * override `icon`, `role`, `principles`, etc., but `slug`, `skillId`, `name`,
 * `title` are immutable.
 */
export interface BmadPersona {
  readonly slug: BmadPersonaSlug;
  readonly skillId: string;
  readonly name: string;
  readonly title: string;
  readonly icon: string;
  readonly module: string;
  readonly team: string;
  readonly description: string;
  readonly phase: BmadPhase;
}

export const BmadPersonaSchema = z.object({
  slug: BmadPersonaSlugSchema,
  skillId: z.string().min(1),
  name: z.string().min(1),
  title: z.string().min(1),
  icon: z.string().min(1),
  module: z.string().min(1),
  team: z.string(),
  description: z.string(),
  phase: BmadPhaseSchema,
});

// =============================================================================
// Skill kinds + skill manifest entries
// =============================================================================

/**
 * BMAD splits skills into three kinds per docs § "Skill Categories":
 * - `agent`     loads a persona (skill id starts with `bmad-agent-*`)
 * - `workflow`  multi-step process (most `_bmad/{module}/N-phase/*` skills)
 * - `task`      standalone task / tool (most core/* skills)
 *
 * The classification isn't carried in skill-manifest.csv directly — it's
 * derived: `bmad-agent-*` prefix → agent; presence of `bmad-help.csv` row
 * with non-empty `output-location` and a multi-step body → workflow; else task.
 * `module-registry.ts` does the classification.
 */
export const BMAD_SKILL_KINDS = ['agent', 'workflow', 'task'] as const;
export type BmadSkillKind = (typeof BMAD_SKILL_KINDS)[number];
export const BmadSkillKindSchema = z.enum(BMAD_SKILL_KINDS);

/**
 * One row of `_bmad/_config/skill-manifest.csv`. Fields:
 *   canonicalId,name,description,module,path
 *
 * `path` is relative to the project root, e.g. `_bmad/bmm/2-plan-workflows/bmad-create-prd/SKILL.md`.
 */
export interface BmadSkillManifestEntry {
  readonly canonicalId: string;
  readonly name: string;
  readonly description: string;
  readonly module: string;
  readonly path: string;
}

export const BmadSkillManifestEntrySchema = z.object({
  canonicalId: z.string().min(1),
  name: z.string().min(1),
  description: z.string(),
  module: z.string().min(1),
  path: z.string().min(1),
});

// =============================================================================
// bmad-help.csv (the phase / dependency graph)
// =============================================================================

/**
 * One row of `_bmad/_config/bmad-help.csv` — the canonical phase-graph database
 * per ENGINE_SWAP_PROMPT.md KAD-3 + `bmad-help/SKILL.md` § "CSV Interpretation".
 *
 * Header: `module,skill,display-name,menu-code,description,action,args,phase,after,before,required,output-location,outputs`
 *
 * Notes:
 * - `_meta` rows hold module-level documentation pointers, not workflows. We
 *   surface them as kind: 'meta' and exclude from the executable graph.
 * - `after` / `before` may reference a specific action with a colon, e.g.
 *   `bmad-create-story:validate`. The `BmadHelpDependency` shape captures both.
 * - `required` is a `false` / `true` literal in the CSV.
 * - `outputs` is pipe-separated (`planning_artifacts|project-knowledge`).
 */
export const BMAD_HELP_ROW_KINDS = ['meta', 'workflow'] as const;
export type BmadHelpRowKind = (typeof BMAD_HELP_ROW_KINDS)[number];

export interface BmadHelpDependency {
  readonly skill: string;
  readonly action: string | null;
}

export const BmadHelpDependencySchema = z.object({
  skill: z.string().min(1),
  action: z.string().nullable(),
});

export interface BmadHelpRow {
  readonly module: string;
  readonly skill: string;
  readonly displayName: string;
  readonly menuCode: string;
  readonly description: string;
  readonly action: string;
  readonly args: string;
  readonly phase: BmadPhase;
  readonly after: readonly BmadHelpDependency[];
  readonly before: readonly BmadHelpDependency[];
  readonly required: boolean;
  readonly outputLocation: string;
  readonly outputs: readonly string[];
  readonly kind: BmadHelpRowKind;
}

export const BmadHelpRowSchema = z.object({
  module: z.string().min(1),
  skill: z.string().min(1),
  displayName: z.string(),
  menuCode: z.string(),
  description: z.string(),
  action: z.string(),
  args: z.string(),
  phase: BmadPhaseSchema,
  after: z.array(BmadHelpDependencySchema).readonly(),
  before: z.array(BmadHelpDependencySchema).readonly(),
  required: z.boolean(),
  outputLocation: z.string(),
  outputs: z.array(z.string()).readonly(),
  kind: z.enum(BMAD_HELP_ROW_KINDS),
});

// =============================================================================
// Manifest (manifest.yaml) and module records
// =============================================================================

/**
 * `_bmad/_config/manifest.yaml` shape. Per BMAD docs § "What got installed".
 * `source` distinguishes built-in modules (core, bmm) from external Git-backed,
 * community marketplace, and custom-source modules.
 */
export const BMAD_MODULE_SOURCES = ['built-in', 'external', 'community', 'custom'] as const;
export type BmadModuleSource = (typeof BMAD_MODULE_SOURCES)[number];

export const BMAD_MODULE_CHANNELS = ['stable', 'next', 'pinned'] as const;
export type BmadModuleChannel = (typeof BMAD_MODULE_CHANNELS)[number];

export interface BmadModule {
  readonly name: string;
  readonly version: string;
  readonly installDate: string;
  readonly lastUpdated: string;
  readonly source: BmadModuleSource;
  readonly channel?: BmadModuleChannel;
  readonly sha?: string;
  readonly npmPackage: string | null;
  readonly repoUrl: string | null;
  readonly localPath?: string;
}

export const BmadModuleSchema = z.object({
  name: z.string().min(1),
  version: z.string().min(1),
  installDate: z.string().min(1),
  lastUpdated: z.string().min(1),
  source: z.enum(BMAD_MODULE_SOURCES),
  channel: z.enum(BMAD_MODULE_CHANNELS).optional(),
  sha: z.string().optional(),
  npmPackage: z.string().nullable(),
  repoUrl: z.string().nullable(),
  localPath: z.string().optional(),
});

export interface BmadInstallation {
  readonly version: string;
  readonly installDate: string;
  readonly lastUpdated: string;
}

export const BmadInstallationSchema = z.object({
  version: z.string().min(1),
  installDate: z.string().min(1),
  lastUpdated: z.string().min(1),
});

export interface BmadManifest {
  readonly installation: BmadInstallation;
  readonly modules: readonly BmadModule[];
  readonly ides: readonly string[];
}

export const BmadManifestSchema = z.object({
  installation: BmadInstallationSchema,
  modules: z.array(BmadModuleSchema).readonly(),
  ides: z.array(z.string()).readonly(),
});

// =============================================================================
// files-manifest.csv
// =============================================================================

/**
 * One row of `_bmad/_config/files-manifest.csv` — installer's per-file SHA-256
 * record used for drift detection. Header: `type,name,module,path,hash`.
 */
export interface BmadFilesManifestEntry {
  readonly type: string;
  readonly name: string;
  readonly module: string;
  readonly path: string;
  readonly hash: string;
}

export const BmadFilesManifestEntrySchema = z.object({
  type: z.string().min(1),
  name: z.string().min(1),
  module: z.string().min(1),
  path: z.string().min(1),
  hash: z.string().min(1),
});

// =============================================================================
// Skill artifact (parsed SKILL.md + step files + customize.toml)
// =============================================================================

/**
 * Step files live in one of `steps/`, `steps-c/` (create), `steps-e/` (edit),
 * `steps-v/` (validate), per inspection of installed skills. The `category`
 * here is the directory name; `index` is parsed from filenames like `1-foo.md`,
 * `step-1.md`, etc.
 */
export const BMAD_STEP_CATEGORIES = ['steps', 'steps-c', 'steps-e', 'steps-v'] as const;
export type BmadStepCategory = (typeof BMAD_STEP_CATEGORIES)[number];

export interface BmadStepFile {
  readonly category: BmadStepCategory;
  readonly fileName: string;
  readonly absolutePath: string;
  readonly index: number | null;
}

export const BmadStepFileSchema = z.object({
  category: z.enum(BMAD_STEP_CATEGORIES),
  fileName: z.string().min(1),
  absolutePath: z.string().min(1),
  index: z.number().int().nullable(),
});

/**
 * SKILL.md frontmatter is YAML with at least `name` and `description`. Some
 * skills include extras (`category`, `module`, `version`, ...). We capture the
 * known keys and stash the rest under `extra`.
 */
export interface BmadSkillFrontmatter {
  readonly name: string;
  readonly description: string;
  readonly extra: Readonly<Record<string, unknown>>;
}

export const BmadSkillFrontmatterSchema = z.object({
  name: z.string().min(1),
  description: z.string(),
  extra: z.record(z.string(), z.unknown()).readonly(),
});

/**
 * Result of `SkillRegistry.load(skillId)`. The `customizationDefaults` field
 * holds the parsed `customize.toml`; `customizationResolved` holds the
 * three-layer merged result for the active project (per KAD-5 + BMAD docs
 * § "Three-Layer Override Model").
 */
export interface BmadSkill {
  readonly canonicalId: string;
  readonly module: string;
  readonly skillDir: string;
  readonly manifestPath: string;
  readonly kind: BmadSkillKind;
  readonly frontmatter: BmadSkillFrontmatter;
  readonly body: string;
  readonly stepFiles: readonly BmadStepFile[];
  readonly customizationDefaults: Readonly<Record<string, unknown>> | null;
  readonly customizationResolved: Readonly<Record<string, unknown>> | null;
}

export const BmadSkillSchema = z.object({
  canonicalId: z.string().min(1),
  module: z.string().min(1),
  skillDir: z.string().min(1),
  manifestPath: z.string().min(1),
  kind: BmadSkillKindSchema,
  frontmatter: BmadSkillFrontmatterSchema,
  body: z.string(),
  stepFiles: z.array(BmadStepFileSchema).readonly(),
  customizationDefaults: z.record(z.string(), z.unknown()).nullable(),
  customizationResolved: z.record(z.string(), z.unknown()).nullable(),
});

// =============================================================================
// Customization (per-skill three-layer TOML)
// =============================================================================

/**
 * Per BMAD docs § "Three-Layer Override Model":
 *   Priority 1: _bmad/custom/{skill}.user.toml  (personal, gitignored)
 *   Priority 2: _bmad/custom/{skill}.toml       (team, committed)
 *   Priority 3: {skill}/customize.toml          (defaults)
 */
export const BMAD_CUSTOMIZATION_SCOPES = ['team', 'user'] as const;
export type BmadCustomizationScope = (typeof BMAD_CUSTOMIZATION_SCOPES)[number];

export interface BmadCustomizationOverride {
  readonly skillName: string;
  readonly scope: BmadCustomizationScope;
  readonly data: Readonly<Record<string, unknown>>;
}

export const BmadCustomizationOverrideSchema = z.object({
  skillName: z.string().min(1),
  scope: z.enum(BMAD_CUSTOMIZATION_SCOPES),
  data: z.record(z.string(), z.unknown()).readonly(),
});

// =============================================================================
// Phase 5: brownfield migration (.auto-claude/specs -> _bmad-output)
// =============================================================================

export interface BmadMigrationCandidate {
  readonly id: string;
  readonly title: string;
  readonly sourceDir: string;
  readonly hasSpec: boolean;
  readonly hasImplementationPlan: boolean;
  readonly hasRequirements: boolean;
}

export const BmadMigrationCandidateSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  sourceDir: z.string().min(1),
  hasSpec: z.boolean(),
  hasImplementationPlan: z.boolean(),
  hasRequirements: z.boolean(),
});

export interface BmadMigrationPlan {
  readonly projectRoot: string;
  readonly hasLegacySpecs: boolean;
  readonly specsDir: string;
  readonly backupDir: string;
  readonly candidates: readonly BmadMigrationCandidate[];
}

export const BmadMigrationPlanSchema = z.object({
  projectRoot: z.string().min(1),
  hasLegacySpecs: z.boolean(),
  specsDir: z.string().min(1),
  backupDir: z.string().min(1),
  candidates: z.array(BmadMigrationCandidateSchema).readonly(),
});

export interface BmadMigrationResult extends BmadMigrationPlan {
  readonly migrated: boolean;
  readonly planningFiles: readonly string[];
  readonly implementationFiles: readonly string[];
  readonly sprintStatusPath: string | null;
}

export const BmadMigrationResultSchema = BmadMigrationPlanSchema.extend({
  migrated: z.boolean(),
  planningFiles: z.array(z.string()).readonly(),
  implementationFiles: z.array(z.string()).readonly(),
  sprintStatusPath: z.string().nullable(),
});

// =============================================================================
// Sprint status (Phase 2 reads/writes; types live here for cross-phase reuse)
// =============================================================================

/**
 * Story statuses come from the sprint-status template at
 * `~/Projects/BMAD-Install-Files/.agents/skills/bmad-sprint-planning/sprint-status-template.yaml`
 * and BMAD docs § "The Build Cycle". The Kanban (Phase 3) maps these onto its
 * 5 columns plus an Optional lane (KAD-8).
 */
export const BMAD_STORY_STATUSES = [
  'backlog',
  'ready-for-dev',
  'in-progress',
  'review',
  'done',
] as const;
export type BmadStoryStatus = (typeof BMAD_STORY_STATUSES)[number];

export const BmadStoryStatusSchema = z.enum(BMAD_STORY_STATUSES);

// =============================================================================
// File watcher events (renderer-visible)
// =============================================================================

/**
 * Typed events emitted by `file-watcher.ts`. The watcher debounces raw chokidar
 * events at 250ms and buckets them into these categories. Renderer subscribes
 * via the `BmadAPI.onFileEvent` listener.
 */
export const BMAD_FILE_EVENT_TYPES = [
  'manifest-changed',
  'skill-changed',
  'customization-changed',
  'sprint-status-changed',
  'story-file-changed',
  'epic-file-changed',
  'config-changed',
  'project-context-changed',
  'planning-artifact-changed',
  'implementation-artifact-changed',
] as const;

export type BmadFileEventType = (typeof BMAD_FILE_EVENT_TYPES)[number];
export const BmadFileEventTypeSchema = z.enum(BMAD_FILE_EVENT_TYPES);

export interface BmadFileEvent {
  readonly type: BmadFileEventType;
  readonly path: string;
  readonly projectRoot: string;
  readonly timestamp: number;
}

export const BmadFileEventSchema = z.object({
  type: BmadFileEventTypeSchema,
  path: z.string().min(1),
  projectRoot: z.string().min(1),
  timestamp: z.number().int().nonnegative(),
});

// =============================================================================
// Installer
// =============================================================================

/**
 * Every flag from BMAD docs § "Headless CI installs". The installer wrapper
 * accepts these as a typed object; it never accepts a free-form string array
 * (that would defeat shell-injection safety per `<engineering_standards>`).
 *
 * `customSource` accepts comma-separated values per BMAD docs
 * § "Custom Sources (Git URLs and Local Paths)" Multi-source recipe.
 */
export const BMAD_INSTALLER_ACTIONS = ['install', 'update', 'quick-update'] as const;
export type BmadInstallerAction = (typeof BMAD_INSTALLER_ACTIONS)[number];

export interface BmadInstallerOptions {
  readonly directory: string;
  readonly yes?: boolean;
  readonly modules?: readonly string[];
  readonly tools?: readonly string[];
  readonly action?: BmadInstallerAction;
  readonly customSource?: readonly string[];
  readonly channel?: BmadModuleChannel;
  readonly allStable?: boolean;
  readonly allNext?: boolean;
  readonly next?: readonly string[];
  readonly pin?: Readonly<Record<string, string>>;
  readonly set?: Readonly<Record<string, string>>;
  readonly userName?: string;
  readonly communicationLanguage?: string;
  readonly documentOutputLanguage?: string;
  readonly outputFolder?: string;
  readonly githubToken?: string;
  /** Use `npx bmad-method@next install` instead of default channel. */
  readonly useNextChannel?: boolean;
}

/**
 * One streamed line of installer stdout/stderr, typed for IPC delivery.
 * `kind: 'progress'` carries semantic events like "Module installed" parsed
 * from the installer's structured output (`◇  N module(s) installed`).
 */
export const BMAD_INSTALLER_STREAM_KINDS = ['stdout', 'stderr', 'progress'] as const;
export type BmadInstallerStreamKind = (typeof BMAD_INSTALLER_STREAM_KINDS)[number];

export interface BmadInstallerStreamChunk {
  readonly kind: BmadInstallerStreamKind;
  readonly text: string;
  readonly timestamp: number;
  /** Parsed semantic event when `kind === 'progress'`. */
  readonly progress?: BmadInstallerProgressEvent;
}

export const BMAD_INSTALLER_PROGRESS_EVENTS = [
  'started',
  'shared-scripts-installed',
  'module-installing',
  'modules-installed',
  'directories-created',
  'configurations-generated',
  'tool-configured',
  'completed',
] as const;

export type BmadInstallerProgressEventName = (typeof BMAD_INSTALLER_PROGRESS_EVENTS)[number];

export interface BmadInstallerProgressEvent {
  readonly event: BmadInstallerProgressEventName;
  readonly detail?: string;
}

/** Final result of a finished install run. */
export interface BmadInstallerResult {
  readonly exitCode: number;
  readonly success: boolean;
  readonly directory: string;
  readonly durationMs: number;
  readonly bmadDirCreated: boolean;
  readonly modules: readonly string[];
  readonly tools: readonly string[];
  readonly skillsConfigured: number;
  readonly raw: string;
}

export const BmadInstallerResultSchema = z.object({
  exitCode: z.number().int(),
  success: z.boolean(),
  directory: z.string().min(1),
  durationMs: z.number().int().nonnegative(),
  bmadDirCreated: z.boolean(),
  modules: z.array(z.string()).readonly(),
  tools: z.array(z.string()).readonly(),
  skillsConfigured: z.number().int().nonnegative(),
  raw: z.string(),
});

// =============================================================================
// IPC envelope (BMAD-specific structured-error variant)
// =============================================================================

/**
 * Structured BMAD error codes. The set is closed (no string fallback) to keep
 * the renderer's error UX exhaustive. Add a code here, then translate it in
 * `apps/desktop/src/shared/i18n/locales/{en,fr}/bmad.json` under `errors.*`.
 *
 * Per ENGINE_SWAP_PROMPT.md `<engineering_standards>` "Error handling": every
 * IPC handler returns `{ ok: false, error: { code, message, details } }`. We
 * use `success` (matching the existing `IPCResult<T>` convention from
 * `apps/desktop/src/shared/types/common.ts`) instead of `ok` to keep one IPC
 * envelope verb in the codebase. The structured `error` body is the
 * substantive change. Logged in DECISIONS.md as D-007.
 */
export const BMAD_ERROR_CODES = [
  'INSTALLER_NOT_FOUND',
  'INSTALLER_FAILED',
  'INSTALLER_TIMEOUT',
  'INSTALLER_ALREADY_RUNNING',
  'NPX_NOT_AVAILABLE',
  'PROJECT_NOT_BMAD',
  'PROJECT_NOT_FOUND',
  'MANIFEST_PARSE_ERROR',
  'CSV_PARSE_ERROR',
  'TOML_PARSE_ERROR',
  'YAML_PARSE_ERROR',
  'SKILL_NOT_FOUND',
  'SKILL_PARSE_ERROR',
  'STEP_FILE_NOT_FOUND',
  'STEP_LOAD_VIOLATION',
  'PATH_OUT_OF_PROJECT',
  'CUSTOMIZATION_VALIDATION_ERROR',
  'CUSTOMIZATION_WRITE_FAILED',
  'CUSTOMIZATION_READ_FAILED',
  'WATCHER_INIT_FAILED',
  'WATCHER_NOT_RUNNING',
  // Phase 2 additions
  'PROVIDER_ERROR',
  'UNSUPPORTED_TRACK',
  'CYCLIC_VARIABLE',
  'SPRINT_STATUS_NOT_FOUND',
  'SPRINT_STATUS_VALIDATION_ERROR',
  'SPRINT_STATUS_WRITE_FAILED',
  'WORKFLOW_MAX_TURNS',
  'PERSONA_NOT_FOUND',
  'PERSONA_PARSE_ERROR',
  // Phase 5 additions
  'MIGRATION_NOT_FOUND',
  'MIGRATION_BACKUP_FAILED',
  'MIGRATION_WRITE_FAILED',
  // Generic
  'IO_ERROR',
  'INVALID_INPUT',
  'UNKNOWN',
] as const;

export type BmadErrorCode = (typeof BMAD_ERROR_CODES)[number];

export interface BmadError {
  readonly code: BmadErrorCode;
  readonly message: string;
  readonly details?: unknown;
}

export const BmadErrorSchema = z.object({
  code: z.enum(BMAD_ERROR_CODES),
  message: z.string().min(1),
  details: z.unknown().optional(),
});

export type BmadIpcResult<T = unknown> =
  | { readonly success: true; readonly data: T }
  | { readonly success: false; readonly error: BmadError };

/**
 * Construct an "ok" envelope. Inline-friendly for handler bodies.
 */
export function bmadOk<T>(data: T): BmadIpcResult<T> {
  return { success: true, data };
}

/**
 * Construct a structured-error envelope. `details` may be any JSON-serializable
 * value (Zod issue list, raw stderr, etc.) — the renderer treats it as opaque
 * data attached to the error code.
 */
export function bmadFail<T = never>(
  code: BmadErrorCode,
  message: string,
  details?: unknown,
): BmadIpcResult<T> {
  return { success: false, error: { code, message, details } };
}

// =============================================================================
// Cross-cutting summary types (consumed by the renderer)
// =============================================================================

/**
 * High-level project summary returned by `BmadAPI.detectProject(projectRoot)`.
 * `isBmadProject: false` means `_bmad/_config/manifest.yaml` is missing — the
 * renderer should offer to run the installer.
 */
export interface BmadProjectSummary {
  readonly projectRoot: string;
  readonly isBmadProject: boolean;
  readonly manifest: BmadManifest | null;
  readonly skillCount: number;
  readonly moduleCount: number;
}

export const BmadProjectSummarySchema = z.object({
  projectRoot: z.string().min(1),
  isBmadProject: z.boolean(),
  manifest: BmadManifestSchema.nullable(),
  skillCount: z.number().int().nonnegative(),
  moduleCount: z.number().int().nonnegative(),
});

/**
 * Workflow descriptor surfaced to the orchestrator + Kanban (Phase 2 + 3).
 * Built from `bmad-help.csv` row + skill manifest entry.
 */
export interface BmadWorkflowDescriptor {
  readonly skillId: string;
  readonly module: string;
  readonly displayName: string;
  readonly description: string;
  readonly menuCode: string;
  readonly action: string;
  readonly args: string;
  readonly phase: BmadPhase;
  readonly required: boolean;
  readonly after: readonly BmadHelpDependency[];
  readonly before: readonly BmadHelpDependency[];
  readonly outputLocation: string;
  readonly outputs: readonly string[];
  readonly skillPath: string;
}

export const BmadWorkflowDescriptorSchema = z.object({
  skillId: z.string().min(1),
  module: z.string().min(1),
  displayName: z.string(),
  description: z.string(),
  menuCode: z.string(),
  action: z.string(),
  args: z.string(),
  phase: BmadPhaseSchema,
  required: z.boolean(),
  after: z.array(BmadHelpDependencySchema).readonly(),
  before: z.array(BmadHelpDependencySchema).readonly(),
  outputLocation: z.string(),
  outputs: z.array(z.string()).readonly(),
  skillPath: z.string().min(1),
});

/**
 * Phase graph slice the orchestrator hands to the Kanban. `requiredWorkflows`
 * is the gate set for the active track; `optionalWorkflows` is the suggestion
 * surface (Phase 1 of the lifecycle has no required workflows by definition).
 */
export interface BmadPhaseSlice {
  readonly phase: BmadPhase;
  readonly requiredWorkflows: readonly BmadWorkflowDescriptor[];
  readonly optionalWorkflows: readonly BmadWorkflowDescriptor[];
}

export const BmadPhaseSliceSchema = z.object({
  phase: BmadPhaseSchema,
  requiredWorkflows: z.array(BmadWorkflowDescriptorSchema).readonly(),
  optionalWorkflows: z.array(BmadWorkflowDescriptorSchema).readonly(),
});

/**
 * Full phase graph the renderer caches once per project (re-emitted on every
 * `manifest-changed` watcher event).
 */
export interface BmadPhaseGraph {
  readonly slices: readonly BmadPhaseSlice[];
  readonly anytimeWorkflows: readonly BmadWorkflowDescriptor[];
}

export const BmadPhaseGraphSchema = z.object({
  slices: z.array(BmadPhaseSliceSchema).readonly(),
  anytimeWorkflows: z.array(BmadWorkflowDescriptorSchema).readonly(),
});

// =============================================================================
// Phase 2: Persona identity (resolved persona block)
// =============================================================================

/**
 * Persona identity at runtime — the merged result of `_bmad/config.toml`
 * `[agents.bmad-agent-*]` (immutable name/title/module/team) plus the
 * persona's own `customize.toml` `[agent]` block (icon/role/principles/menu).
 *
 * Per BMAD docs § "What Named Agents Buy You": `name` and `title` are
 * read-only identity. Everything else is customizable via the three-layer
 * TOML cascade (KAD-5).
 */
export interface BmadPersonaIdentity {
  /** Slug from the hardcoded BmadPersonaSlug union. */
  readonly slug: BmadPersonaSlug;
  /** Skill id this persona belongs to (e.g. `bmad-agent-pm`). */
  readonly skillId: string;
  /** Read-only identity from `_bmad/config.toml [agents.{skillId}]`. */
  readonly name: string;
  readonly title: string;
  readonly module: string;
  readonly team: string;
  readonly description: string;
  /**
   * Customizable surface (from per-skill `customize.toml [agent]`, possibly
   * overridden by `_bmad/custom/{skillId}.toml` and `.user.toml`).
   */
  readonly icon: string;
  readonly role: string;
  readonly identity: string;
  readonly communicationStyle: string;
  readonly principles: readonly string[];
  readonly persistentFacts: readonly string[];
  readonly activationStepsPrepend: readonly string[];
  readonly activationStepsAppend: readonly string[];
  readonly menu: readonly BmadPersonaMenuItem[];
  /** Lifecycle phase the persona is anchored to (informational; orchestrator
   *  uses `bmad-help.csv` rows for routing, not this). */
  readonly phase: BmadPhase;
}

export interface BmadPersonaMenuItem {
  readonly code: string;
  readonly description: string;
  /** One of `skill` or `prompt` is set per BMAD docs § "Customization as a First-Class Citizen". */
  readonly skill?: string;
  readonly prompt?: string;
}

export const BmadPersonaMenuItemSchema = z.object({
  code: z.string().min(1),
  description: z.string(),
  skill: z.string().optional(),
  prompt: z.string().optional(),
});

export const BmadPersonaIdentitySchema = z.object({
  slug: BmadPersonaSlugSchema,
  skillId: z.string().min(1),
  name: z.string().min(1),
  title: z.string().min(1),
  module: z.string().min(1),
  team: z.string(),
  description: z.string(),
  icon: z.string(),
  role: z.string(),
  identity: z.string(),
  communicationStyle: z.string(),
  principles: z.array(z.string()).readonly(),
  persistentFacts: z.array(z.string()).readonly(),
  activationStepsPrepend: z.array(z.string()).readonly(),
  activationStepsAppend: z.array(z.string()).readonly(),
  menu: z.array(BmadPersonaMenuItemSchema).readonly(),
  phase: BmadPhaseSchema,
});

// =============================================================================
// Phase 2: Variable context (resolved central config + computed runtime values)
// =============================================================================

/**
 * Substitution context passed to `substituteVariables(text, ctx)`. Every
 * key listed here is a recognized BMAD variable per Phase 2 deliverable §3:
 * `{project-root}`, `{skill-root}`, `{skill-name}`, `{user_name}`,
 * `{communication_language}`, `{document_output_language}`,
 * `{planning_artifacts}`, `{implementation_artifacts}`, `{project_knowledge}`,
 * `{output_folder}`, `{date}`, plus the optional `{user_skill_level}` from
 * `bmad-dev-story` (per its SKILL.md Step 4).
 *
 * Resolved from `_bmad/config.toml [core]` + `_bmad/{module}/config.yaml` per
 * BMAD docs § "Step 4: Load Config" of every workflow's activation flow.
 */
export interface BmadVariableContext {
  readonly projectRoot: string;
  readonly skillRoot: string;
  readonly skillName: string;
  readonly userName: string;
  readonly communicationLanguage: string;
  readonly documentOutputLanguage: string;
  readonly planningArtifacts: string;
  readonly implementationArtifacts: string;
  readonly projectKnowledge: string;
  readonly outputFolder: string;
  readonly date: string;
  /** Optional, present only for skills that use it (e.g. bmad-dev-story). */
  readonly userSkillLevel?: string;
  /** Project name from `_bmad/config.toml [core] project_name`. */
  readonly projectName: string;
}

// =============================================================================
// Phase 2: Workflow runner contracts
// =============================================================================

/**
 * One streamed event from a running workflow. The runner emits these via
 * the `onStreamChunk` callback so the renderer can render incremental text,
 * tool calls, and step transitions.
 */
export const BMAD_WORKFLOW_STREAM_KINDS = [
  'text-delta',
  'tool-call',
  'tool-result',
  'reasoning',
  'step-start',
  'step-finish',
  'menu',
  'error',
  'done',
] as const;
export type BmadWorkflowStreamKind = (typeof BMAD_WORKFLOW_STREAM_KINDS)[number];

export interface BmadWorkflowStreamChunk {
  readonly kind: BmadWorkflowStreamKind;
  readonly text?: string;
  readonly toolName?: string;
  readonly toolArgs?: Record<string, unknown>;
  readonly toolResult?: unknown;
  /** Step file context — set on `step-start` / `step-finish` events. */
  readonly stepFileName?: string;
  /** Sequence number for ordering on the renderer side. */
  readonly seq: number;
  readonly timestamp: number;
}

/**
 * Workflow step descriptor — surfaced when the runner loads a new step file.
 * Mirrors `BmadStepFile` (which describes a step file on disk) plus the
 * loaded body content the runner injected as a system addendum.
 */
export interface BmadWorkflowStep {
  readonly index: number;
  readonly fileName: string;
  readonly absolutePath: string;
  readonly category: BmadStepCategory;
  /** The full step file body, post-variable-substitution. */
  readonly body: string;
}

export const BmadWorkflowStepSchema = z.object({
  index: z.number().int().nonnegative(),
  fileName: z.string().min(1),
  absolutePath: z.string().min(1),
  category: z.enum(BMAD_STEP_CATEGORIES),
  body: z.string(),
});

/**
 * Interactive menu surfaced to the renderer when the model halts and waits
 * for user input. The runner uses a heuristic to detect numbered menus
 * (e.g., `[C] Continue`, `1. Pick this`) in the model's last response;
 * when none is detected, the renderer should treat the prompt as a free-form
 * input and call `resolveMenu({ text: <freeform> })`.
 */
export interface BmadWorkflowMenuOption {
  readonly code: string;
  readonly label: string;
}

export interface BmadWorkflowMenu {
  readonly prompt: string;
  readonly options: readonly BmadWorkflowMenuOption[];
}

export const BmadWorkflowMenuOptionSchema = z.object({
  code: z.string().min(1),
  label: z.string().min(1),
});

export const BmadWorkflowMenuSchema = z.object({
  prompt: z.string(),
  options: z.array(BmadWorkflowMenuOptionSchema).readonly(),
});

/**
 * User's response to a workflow menu. Either `optionCode` (matching one of
 * the menu options) or free-form `text` (or both — text describes intent,
 * code disambiguates among matching options).
 */
export interface BmadWorkflowUserChoice {
  readonly optionCode?: string;
  readonly text: string;
}

export const BmadWorkflowUserChoiceSchema = z.object({
  optionCode: z.string().optional(),
  text: z.string(),
});

/**
 * Final result of one `runWorkflow()` invocation. The runner returns this
 * after the workflow signals completion (model says "complete" or step file
 * indicates terminal state) or the user aborts.
 */
export const BMAD_WORKFLOW_OUTCOMES = [
  'completed',
  'aborted',
  'error',
  'max_turns',
] as const;
export type BmadWorkflowOutcome = (typeof BMAD_WORKFLOW_OUTCOMES)[number];

export interface BmadWorkflowResult {
  readonly outcome: BmadWorkflowOutcome;
  readonly skillId: string;
  readonly turns: number;
  readonly durationMs: number;
  readonly outputFiles: readonly string[];
  readonly error?: BmadError;
}

export const BmadWorkflowResultSchema = z.object({
  outcome: z.enum(BMAD_WORKFLOW_OUTCOMES),
  skillId: z.string().min(1),
  turns: z.number().int().nonnegative(),
  durationMs: z.number().int().nonnegative(),
  outputFiles: z.array(z.string()).readonly(),
  error: BmadErrorSchema.optional(),
});

// =============================================================================
// Phase 2: Sprint status (Zod schema for sprint-status.yaml)
// =============================================================================

/**
 * Parsed `_bmad-output/implementation-artifacts/sprint-status.yaml`. Schema
 * sourced from `~/Projects/BMAD-Install-Files/.agents/skills/bmad-sprint-planning/sprint-status-template.yaml`.
 *
 * - `developmentStatus` keys: `epic-N` for epic rows, `epic-N-retrospective`
 *   for the optional retro lane, `N-M-name` for stories. The Kanban groups
 *   stories under their epic by parsing the leading number.
 * - Status values: `BMAD_STORY_STATUSES` for stories + `optional`/`done` for
 *   retros + `backlog`/`in-progress`/`done` for epics. We accept the wider
 *   `BMAD_DEVELOPMENT_STATUS` union for forward-compat with future modules.
 */
export const BMAD_DEVELOPMENT_STATUSES = [
  'backlog',
  'ready-for-dev',
  'in-progress',
  'review',
  'done',
  'optional',
] as const;
export type BmadDevelopmentStatus = (typeof BMAD_DEVELOPMENT_STATUSES)[number];
export const BmadDevelopmentStatusSchema = z.enum(BMAD_DEVELOPMENT_STATUSES);

export interface BmadSprintStatus {
  readonly generated: string;
  readonly lastUpdated: string;
  readonly project: string;
  readonly projectKey: string;
  readonly trackingSystem: string;
  readonly storyLocation: string;
  readonly developmentStatus: Readonly<Record<string, BmadDevelopmentStatus>>;
}

export const BmadSprintStatusSchema = z.object({
  generated: z.string(),
  lastUpdated: z.string(),
  project: z.string(),
  projectKey: z.string(),
  trackingSystem: z.string(),
  storyLocation: z.string(),
  developmentStatus: z.record(z.string(), BmadDevelopmentStatusSchema),
});

// =============================================================================
// Phase 2: Orchestrator events
// =============================================================================

/**
 * Events emitted by `BmadOrchestrator` as the project progresses through
 * the four lifecycle phases. The renderer subscribes via IPC; the orchestrator
 * recomputes state on every `manifest-changed` / `sprint-status-changed` /
 * `planning-artifact-changed` watcher event.
 */
export const BMAD_ORCHESTRATOR_EVENT_KINDS = [
  'phase-progressed',
  'workflow-required',
  'workflow-recommended',
  'workflow-completed',
  'phase-complete',
  'track-complete',
] as const;
export type BmadOrchestratorEventKind = (typeof BMAD_ORCHESTRATOR_EVENT_KINDS)[number];

export interface BmadWorkflowAction {
  readonly skillId: string;
  readonly action: string;
  readonly displayName: string;
  readonly menuCode: string;
  readonly description: string;
  readonly phase: BmadPhase;
  readonly required: boolean;
  readonly persona: BmadPersonaSlug | null;
  /** Why the orchestrator is recommending this — sourced from `bmad-help.csv`
   *  `after`/`before` columns + the project's current artifact state. */
  readonly rationale: string;
}

export const BmadWorkflowActionSchema = z.object({
  skillId: z.string().min(1),
  action: z.string(),
  displayName: z.string(),
  menuCode: z.string(),
  description: z.string(),
  phase: BmadPhaseSchema,
  required: z.boolean(),
  persona: BmadPersonaSlugSchema.nullable(),
  rationale: z.string(),
});

export interface BmadOrchestratorEvent {
  readonly kind: BmadOrchestratorEventKind;
  readonly projectRoot: string;
  readonly currentPhase: BmadPhase;
  readonly action?: BmadWorkflowAction;
  readonly timestamp: number;
}

export const BmadOrchestratorEventSchema = z.object({
  kind: z.enum(BMAD_ORCHESTRATOR_EVENT_KINDS),
  projectRoot: z.string().min(1),
  currentPhase: BmadPhaseSchema,
  action: BmadWorkflowActionSchema.optional(),
  timestamp: z.number().int().nonnegative(),
});

/**
 * The orchestrator's "what now?" snapshot. Computed on demand; updated on
 * every relevant watcher event. Mirrors `bmad-help`'s structured output shape
 * per the Phase 4 sidebar's data contract.
 */
export interface BmadHelpRecommendation {
  readonly currentPhase: BmadPhase;
  readonly required: BmadWorkflowAction | null;
  readonly recommended: readonly BmadWorkflowAction[];
  readonly completed: readonly BmadWorkflowAction[];
  readonly track: BmadTrack;
}

export const BmadHelpRecommendationSchema = z.object({
  currentPhase: BmadPhaseSchema,
  required: BmadWorkflowActionSchema.nullable(),
  recommended: z.array(BmadWorkflowActionSchema).readonly(),
  completed: z.array(BmadWorkflowActionSchema).readonly(),
  track: BmadTrackSchema,
});

// =============================================================================
// Phase 3: Kanban view shapes
// =============================================================================

/**
 * Five Kanban columns sourced verbatim from the sprint-status template at
 * `~/Projects/BMAD-Install-Files/.agents/skills/bmad-sprint-planning/sprint-status-template.yaml`.
 * Per ENGINE_SWAP_PROMPT.md KAD-8 — these are the exact YAML status values
 * for stories. Retro rows live in a separate "optional" lane below the board.
 */
export const BMAD_KANBAN_COLUMNS = [
  'backlog',
  'ready-for-dev',
  'in-progress',
  'review',
  'done',
] as const;

export type BmadKanbanColumnId = (typeof BMAD_KANBAN_COLUMNS)[number];
export const BmadKanbanColumnIdSchema = z.enum(BMAD_KANBAN_COLUMNS);

/**
 * Logical card shape for the Kanban. Built from sprint-status.yaml's
 * `development_status` map by `groupSprintStatusIntoEpics`.
 *
 * - `kind: 'story'` — a developer-facing story card. The Kanban renders these
 *   in the 5 columns and they're draggable.
 * - `kind: 'retro'` — `epic-N-retrospective` rows; live in the bottom
 *   "optional" lane and only have two valid statuses (`optional` / `done`).
 */
export const BMAD_STORY_CARD_KINDS = ['story', 'retro'] as const;
export type BmadStoryCardKind = (typeof BMAD_STORY_CARD_KINDS)[number];

export interface BmadStoryView {
  /** Raw key from `development_status` (e.g. `1-2-account-management`). Stable. */
  readonly key: string;
  /** `kind: 'story'` for `N-M-name`; `kind: 'retro'` for `epic-N-retrospective`. */
  readonly kind: BmadStoryCardKind;
  /** Epic id this row belongs to (e.g. `epic-1`). */
  readonly epicId: string;
  /** Numeric epic ordinal extracted from the key (e.g. `1`). */
  readonly epicNumber: number;
  /** Story-within-epic ordinal — null for retro rows. */
  readonly storyNumber: number | null;
  /** Slug component of the key (`account-management`) — null for retro rows. */
  readonly slug: string | null;
  /** Human-readable title — sourced from the story file's H1, falls back to slug. */
  readonly title: string;
  /** Current status from sprint-status.yaml. */
  readonly status: BmadDevelopmentStatus;
  /** Persona who owns this card. Stories → Amelia (per BMAD docs § "Default Agents");
   *  retros → Amelia. Null for unsupported kinds (forward-compat). */
  readonly persona: BmadPersonaSlug | null;
  /**
   * Resolved relative path to the story file (relative to project root).
   * Convention from BMAD's `bmad-create-story` skill:
   *   `_bmad-output/implementation-artifacts/{epicNumber}-{storyNumber}-{slug}.md`
   * Resolved opportunistically; null for retro rows + epic rows.
   */
  readonly storyFilePath: string | null;
  /** Sort hint within an epic. Stories first, then retro at end. */
  readonly orderInEpic: number;
}

export const BmadStoryViewSchema = z.object({
  key: z.string().min(1),
  kind: z.enum(BMAD_STORY_CARD_KINDS),
  epicId: z.string().min(1),
  epicNumber: z.number().int().nonnegative(),
  storyNumber: z.number().int().nonnegative().nullable(),
  slug: z.string().nullable(),
  title: z.string(),
  status: BmadDevelopmentStatusSchema,
  persona: BmadPersonaSlugSchema.nullable(),
  storyFilePath: z.string().nullable(),
  orderInEpic: z.number().int().nonnegative(),
});

/**
 * Epic group rendered under a collapsible header in each Kanban column.
 * Cards are partitioned into `stories` (the main 5 columns) and `retro`
 * (the optional lane). The epic row itself is not draggable — it summarizes
 * its children's progress.
 */
export interface BmadEpicView {
  readonly id: string;
  readonly epicNumber: number;
  readonly title: string;
  readonly status: BmadDevelopmentStatus;
  readonly stories: readonly BmadStoryView[];
  readonly retro: BmadStoryView | null;
}

export const BmadEpicViewSchema = z.object({
  id: z.string().min(1),
  epicNumber: z.number().int().nonnegative(),
  title: z.string(),
  status: BmadDevelopmentStatusSchema,
  stories: z.array(BmadStoryViewSchema).readonly(),
  retro: BmadStoryViewSchema.nullable(),
});

/**
 * Snapshot delivered to the Kanban renderer. Aggregates everything the UI
 * needs from one project — the store consumes this via `useBmadProject`.
 */
export interface BmadKanbanSnapshot {
  readonly projectRoot: string;
  readonly project: string;
  readonly track: BmadTrack;
  readonly currentPhase: BmadPhase;
  readonly sprintStatus: BmadSprintStatus | null;
  readonly epics: readonly BmadEpicView[];
  readonly recommendation: BmadHelpRecommendation | null;
}

// =============================================================================
// Phase 4: Chat thread shapes (BmadPersonaChat)
// =============================================================================

/**
 * One message inside a `BmadChatThread`. Three roles per BMAD docs §
 * "The Activation Flow":
 *   - `assistant` — model output (Mary/John/etc, prefixed with their icon)
 *   - `user` — the human's input (greeting, menu choices, free-form replies)
 *   - `system` — UI-only narration (e.g. "Workflow started", "Step 2 loaded")
 */
export const BMAD_CHAT_MESSAGE_ROLES = ['assistant', 'user', 'system'] as const;
export type BmadChatMessageRole = (typeof BMAD_CHAT_MESSAGE_ROLES)[number];

/**
 * Chat thread message rendered in the persona chat dock. Built by appending
 * stream chunks (text deltas concatenate into one assistant message until
 * the next user input or workflow completion).
 */
export interface BmadChatMessage {
  readonly id: string;
  readonly role: BmadChatMessageRole;
  /** Markdown body. Tool calls render as inline blocks via system messages. */
  readonly content: string;
  /** Persona slug for assistant messages (drives icon + name in the bubble). */
  readonly personaSlug?: BmadPersonaSlug;
  readonly timestamp: number;
  /**
   * Marks an assistant message that's still receiving stream chunks.
   * Cleared when the model halts (menu) or the workflow completes.
   */
  readonly streaming?: boolean;
}

/**
 * Lifecycle status of one workflow invocation. Drives the chat dock's
 * header indicator (loader vs idle vs error vs done).
 */
export const BMAD_CHAT_THREAD_STATUSES = [
  'starting',
  'streaming',
  'awaiting-menu',
  'awaiting-response',
  'completed',
  'aborted',
  'errored',
] as const;
export type BmadChatThreadStatus = (typeof BMAD_CHAT_THREAD_STATUSES)[number];

/**
 * Pending menu surfaced from the workflow runner. The chat UI renders the
 * options as buttons (or a free-form text field when `options` is empty);
 * resolving fires `respondToWorkflowMenu({ invocationId, menuId, choice })`
 * and the thread transitions back to `streaming`.
 */
export interface BmadChatPendingMenu {
  readonly menuId: string;
  readonly menu: BmadWorkflowMenu;
  readonly receivedAt: number;
}

/**
 * Per-invocation chat thread. Multiple threads can coexist (one per running
 * workflow); the dock shows whichever id is `activeChatId` in the store.
 *
 * Per ENGINE_SWAP_PROMPT.md KAD-7 ("Personas persist; chats are fresh") the
 * thread starts with empty messages on every workflow run. Persona persistence
 * is a worker-thread concern, not a chat-history concern.
 */
export interface BmadChatThread {
  readonly invocationId: string;
  readonly skillName: string;
  readonly personaSlug: BmadPersonaSlug | null;
  /** Story key when this thread was started by clicking Run on a card. */
  readonly storyKey: string | null;
  /**
   * `null` until the first chunk arrives. Populated from the workflow runner's
   * skill resolution + persona registry when the renderer launches the call.
   */
  readonly title: string | null;
  /** Streamed messages. Append-only during the thread's lifetime. */
  readonly messages: readonly BmadChatMessage[];
  readonly status: BmadChatThreadStatus;
  /** Pending menu when status === 'awaiting-menu'. */
  readonly pendingMenu: BmadChatPendingMenu | null;
  /** Outcome of the underlying workflow (set on completion). */
  readonly outcome?: BmadWorkflowOutcome;
  /** Error message when status === 'errored'. */
  readonly error?: string;
  readonly startedAt: number;
  readonly endedAt?: number;
}

/**
 * Argument shape used by the renderer-side store action. Matches the IPC
 * payload but does not include `invocationId` (the store generates one
 * locally so it can subscribe to stream events synchronously).
 */
export interface BmadStartWorkflowArgs {
  readonly skillName: string;
  readonly personaSlug?: BmadPersonaSlug;
  readonly storyKey?: string;
  readonly args?: readonly string[];
  readonly maxTurns?: number;
  readonly initialMessages?: ReadonlyArray<{ role: 'user' | 'assistant'; content: string }>;
  /**
   * Optional override for the title shown in the chat header before the
   * first model response arrives. Defaults to the persona's name+title.
   */
  readonly title?: string;
}

/**
 * Argument shape for runHelpAI. The bmad-help skill's narrative streams
 * back into the same chat thread infrastructure as workflows.
 */
export interface BmadStartHelpAIArgs {
  readonly question?: string;
  readonly track?: BmadTrack;
}
