/**
 * BMad persona registry
 * =====================
 *
 * Loads the six hardcoded BMM personas — Mary (📊), Paige (📚), John (📋),
 * Sally (🎨), Winston (🏗️), Amelia (💻) — by joining `_bmad/config.toml`
 * `[agents.bmad-agent-*]` (immutable identity) with each persona's per-skill
 * `customize.toml` `[agent]` block (customizable surface).
 *
 * Per BMAD docs § "What Named Agents Buy You": persona name + title are
 * read-only identity. Icon, role, identity, communication_style, principles,
 * persistent_facts, activation_steps_*, and menu items are all customizable
 * via the three-layer TOML cascade (KAD-5 + § "Three-Layer Override Model").
 *
 * Per ENGINE_SWAP_PROMPT.md KAD-7: a persona loaded into a worker thread
 * stays loaded across multiple workflow invocations within the same project
 * session. Each workflow run starts a fresh `streamText()` conversation but
 * inherits the persona's system prompt.
 *
 * The slug → skillId map is hardcoded — these six personas are the BMM
 * module's defining set per § "Default Agents". Future modules adding
 * personas would extend the registry, but Phase 2 ships only BMM.
 */

import path from 'node:path';
import { resolveConfig } from './config-resolver';
import { getSharedSkillRegistry, SkillRegistry, SkillRegistryError } from './skill-registry';
import {
  BMAD_PERSONA_SLUGS,
  type BmadPersonaIdentity,
  type BmadPersonaMenuItem,
  type BmadPersonaSlug,
  type BmadPhase,
} from '../../../shared/types/bmad';

// =============================================================================
// Errors
// =============================================================================

export class PersonaError extends Error {
  readonly code: 'PERSONA_NOT_FOUND' | 'PERSONA_PARSE_ERROR' | 'IO_ERROR';
  readonly cause?: unknown;
  readonly details?: unknown;

  constructor(
    code: PersonaError['code'],
    message: string,
    options?: { cause?: unknown; details?: unknown },
  ) {
    super(message);
    this.name = 'PersonaError';
    this.code = code;
    if (options?.cause !== undefined) this.cause = options.cause;
    if (options?.details !== undefined) this.details = options.details;
  }
}

// =============================================================================
// Slug ↔ skillId map (hardcoded BMM persona set)
// =============================================================================

/**
 * Six BMM personas with their `bmad-agent-*` skill ids. Slugs are the stable
 * external identifier (used in IPC payloads and UI URLs). Per BMAD docs
 * § "Default Agents" + INVENTORY.md §4.3.
 */
const SLUG_TO_SKILL: Readonly<Record<BmadPersonaSlug, string>> = {
  mary: 'bmad-agent-analyst',
  paige: 'bmad-agent-tech-writer',
  john: 'bmad-agent-pm',
  sally: 'bmad-agent-ux-designer',
  winston: 'bmad-agent-architect',
  amelia: 'bmad-agent-dev',
};

const SKILL_TO_SLUG: ReadonlyMap<string, BmadPersonaSlug> = new Map(
  Object.entries(SLUG_TO_SKILL).map(([slug, skillId]) => [skillId, slug as BmadPersonaSlug]),
);

/**
 * The persona's lifecycle phase anchor. Informational only — the orchestrator
 * routes by `bmad-help.csv` rows, not this map. Source: INVENTORY.md §4.3.
 */
const SLUG_TO_PHASE: Readonly<Record<BmadPersonaSlug, BmadPhase>> = {
  mary: '1-analysis',
  paige: '1-analysis',
  john: '2-planning',
  sally: '2-planning',
  winston: '3-solutioning',
  amelia: '4-implementation',
};

// =============================================================================
// Public API
// =============================================================================

export interface PersonaRegistryOptions {
  readonly projectRoot: string;
  /** Optional shared skill registry (defaults to the singleton). */
  readonly skillRegistry?: SkillRegistry;
}

/**
 * Resolve a single persona by slug. Reads `_bmad/config.toml`, picks the
 * matching `[agents.{skillId}]` block, then loads the skill via the registry
 * to get the merged customization (icon / role / principles / menu).
 *
 * Throws `PERSONA_NOT_FOUND` when the slug isn't one of the six. Throws
 * `IO_ERROR` if the central config or skill can't be loaded.
 */
export async function loadPersona(
  slug: BmadPersonaSlug,
  options: PersonaRegistryOptions,
): Promise<BmadPersonaIdentity> {
  const skillId = SLUG_TO_SKILL[slug];
  if (!skillId) {
    throw new PersonaError('PERSONA_NOT_FOUND', `unknown persona slug: ${slug}`);
  }

  const projectRoot = path.resolve(options.projectRoot);
  const skillRegistry = options.skillRegistry ?? getSharedSkillRegistry();

  // 1. Central config block — `[agents.{skillId}]` lives in `_bmad/config.toml`
  //    and is regenerated by the installer. Read-only identity is here.
  let config: Record<string, unknown>;
  try {
    config = await resolveConfig({ projectRoot });
  } catch (err) {
    throw new PersonaError(
      'IO_ERROR',
      `failed to load _bmad/config.toml: ${(err as Error).message}`,
      { cause: err },
    );
  }

  const agentsBlock = config.agents as Record<string, unknown> | undefined;
  const centralBlock = agentsBlock?.[skillId] as Record<string, unknown> | undefined;
  if (!centralBlock) {
    throw new PersonaError(
      'PERSONA_NOT_FOUND',
      `persona ${slug} (${skillId}) not present in _bmad/config.toml [agents] block`,
    );
  }

  // 2. Per-skill customize.toml [agent] — customizable surface (icon, role,
  //    principles, etc.). Resolved through the three-layer override cascade.
  const skill = await skillRegistry.load(skillId, { projectRoot });
  const agentBlock = (skill.customizationResolved?.agent ?? {}) as Record<string, unknown>;

  return mergePersonaBlocks(slug, skillId, centralBlock, agentBlock);
}

/**
 * Resolve all six BMM personas at once. Returns them in canonical phase
 * order (analysis → planning → solutioning → implementation) so the UI's
 * persona picker doesn't need a sort.
 */
export async function loadAllPersonas(
  options: PersonaRegistryOptions,
): Promise<readonly BmadPersonaIdentity[]> {
  const personas: BmadPersonaIdentity[] = [];
  for (const slug of BMAD_PERSONA_SLUGS) {
    try {
      personas.push(await loadPersona(slug, options));
    } catch (err) {
      // A missing persona means the BMM module isn't installed for this
      // project (no `[agents.bmad-agent-*]` block) OR the per-skill
      // SKILL.md is absent (skill-manifest.csv doesn't list it). Either
      // way, skip silently — the UI shows only the personas that are
      // actually available.
      if (err instanceof PersonaError && err.code === 'PERSONA_NOT_FOUND') continue;
      if (err instanceof SkillRegistryError && err.code === 'SKILL_NOT_FOUND') continue;
      throw err;
    }
  }
  return personas;
}

/**
 * Reverse-lookup: given a `bmad-agent-*` skill id, return its persona slug
 * (or `null` if the skill isn't a known persona). Used by the workflow
 * runner when the user invokes an agent skill directly.
 */
export function personaSlugFromSkillId(skillId: string): BmadPersonaSlug | null {
  return SKILL_TO_SLUG.get(skillId) ?? null;
}

/**
 * Forward-lookup: given a persona slug, return its skill id. Used by IPC
 * handlers that take a slug from the renderer.
 */
export function skillIdForPersonaSlug(slug: BmadPersonaSlug): string {
  return SLUG_TO_SKILL[slug];
}

// =============================================================================
// Internal — block merging
// =============================================================================

/**
 * Merge the central-config block and the per-skill customize block into a
 * single `BmadPersonaIdentity`. Field precedence:
 *   - `name`, `title` come from the central config (read-only identity per
 *     BMAD docs § "Some agent fields are read-only")
 *   - `module`, `team`, `description` come from the central config too
 *   - everything else comes from the per-skill customize.toml [agent] block
 *     (already through the three-layer resolver in skill-registry.ts)
 */
function mergePersonaBlocks(
  slug: BmadPersonaSlug,
  skillId: string,
  central: Record<string, unknown>,
  agent: Record<string, unknown>,
): BmadPersonaIdentity {
  return {
    slug,
    skillId,
    name: stringField(central, 'name'),
    title: stringField(central, 'title'),
    module: stringField(central, 'module'),
    team: stringField(central, 'team'),
    description: stringField(central, 'description'),
    icon: stringField(agent, 'icon'),
    role: stringField(agent, 'role'),
    identity: stringField(agent, 'identity'),
    communicationStyle: stringField(agent, 'communication_style'),
    principles: stringArrayField(agent, 'principles'),
    persistentFacts: stringArrayField(agent, 'persistent_facts'),
    activationStepsPrepend: stringArrayField(agent, 'activation_steps_prepend'),
    activationStepsAppend: stringArrayField(agent, 'activation_steps_append'),
    menu: parseMenu(agent),
    phase: SLUG_TO_PHASE[slug],
  };
}

function stringField(obj: Record<string, unknown>, key: string): string {
  const value = obj[key];
  return typeof value === 'string' ? value : '';
}

function stringArrayField(obj: Record<string, unknown>, key: string): readonly string[] {
  const value = obj[key];
  if (!Array.isArray(value)) return [];
  return value.filter((entry): entry is string => typeof entry === 'string');
}

function parseMenu(agent: Record<string, unknown>): readonly BmadPersonaMenuItem[] {
  const raw = agent.menu;
  if (!Array.isArray(raw)) return [];

  const items: BmadPersonaMenuItem[] = [];
  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue;
    const e = entry as Record<string, unknown>;
    const code = typeof e.code === 'string' ? e.code : '';
    if (!code) continue;

    const description = typeof e.description === 'string' ? e.description : '';
    const skillRef = typeof e.skill === 'string' ? e.skill : undefined;
    const promptRef = typeof e.prompt === 'string' ? e.prompt : undefined;

    items.push({
      code,
      description,
      ...(skillRef ? { skill: skillRef } : {}),
      ...(promptRef ? { prompt: promptRef } : {}),
    });
  }
  return items;
}

// =============================================================================
// Test internals
// =============================================================================

export const __internals = {
  SLUG_TO_SKILL,
  SLUG_TO_PHASE,
  mergePersonaBlocks,
  parseMenu,
};
